/// Builds the privacy policy pages of the project site.
///
/// §16.7 makes a **publicly reachable** privacy policy a condition of
/// publishing at all: Play Console asks for a URL, not a paragraph, and the
/// Data Safety form is checked against what that URL says. So the policy lives
/// on the site rather than in the app, and it is generated through the same
/// skeleton as every other page so it cannot drift out of the site's shape.
///
/// ⚠️ **What it says is checked against what the app does, not remembered.**
/// The manifest's permissions and the one network call the game makes (a map
/// pack download, §16.6) are the whole of it — if either changes, this file is
/// where the answer has to change with it.
///
/// ```
/// dart run tool/build_privacy_pages.dart
/// ```
library;

import 'dart:io';

import 'site_page.dart';

const String kSiteDir = '../ARLS-ZA-Game';

void main() {
  final site = Directory('${Directory.current.path}/$kSiteDir');
  if (!site.existsSync()) {
    stderr.writeln('No site at ${site.path}');
    exitCode = 1;
    return;
  }

  File('${site.path}/privacy.html')
    ..createSync(recursive: true)
    ..writeAsStringSync(_page(pl: false));

  File('${site.path}/pl/privacy.html')
    ..createSync(recursive: true)
    ..writeAsStringSync(_page(pl: true));

  stdout.writeln('privacy policy written to ${site.path}');
}

/// One section: a heading and its paragraphs, already HTML.
typedef _Part = ({
  String id,
  String eyebrow,
  String heading,
  List<String> body,
});

String _page({required bool pl}) {
  final parts = pl ? _partsPl : _partsEn;
  final buffer = StringBuffer();

  buffer.write(
    sitePageOpen(
      pl: pl,
      pageFile: 'privacy.html',
      title: pl ? 'Prywatność' : 'Privacy',
      subtitle: pl
          ? 'Co gra o tobie wie i dokąd to wysyła'
          : 'What the game knows about you, and where it sends it',
      description: pl
          ? 'Polityka prywatności ARLS-ZA: gra nie ma kont, nie zbiera analityki i nie wysyła twojej lokalizacji nigdzie.'
          : 'The ARLS-ZA privacy policy: no accounts, no analytics, and your location is never sent anywhere.',
      eyebrow: pl
          ? 'Obowiązuje od 4 września 2026'
          : 'In force from 4 September 2026',
      thesis: [
        pl
            ? '<strong>Gra nie wysyła niczego nigdzie.</strong> Nie ma kont, nie ma analityki, nie ma raportów awarii i nie ma reklam. Twoja pozycja, liczby twojego ciała i miejsce twojego schronu nie opuszczają telefonu — to nie jest obietnica marketingowa, tylko konsekwencja tego, że gra nie ma żadnych serwerów.'
            : '<strong>The game sends nothing anywhere.</strong> No accounts, no analytics, no crash reports, no advertising. Your position, your body&rsquo;s figures and where your shelter stands never leave the phone — that is not a marketing promise but a consequence of the game having no servers at all.',
      ],
      railTitle: pl ? 'Sekcje' : 'Sections',
      rail: [
        for (final part in parts)
          RailEntry(anchor: part.id, label: part.heading),
      ],
    ),
  );

  for (final part in parts) {
    buffer.writeln('      <section class="sec" id="${part.id}">');
    buffer.writeln('        <div class="sec__hd">');
    buffer.writeln(
      '          <span class="sec__no">${escapeHtml(part.eyebrow)}</span>',
    );
    buffer.writeln('          <h2>${escapeHtml(part.heading)}</h2>');
    buffer.writeln('        </div>');
    buffer.writeln('        <div class="prose">');
    for (final paragraph in part.body) {
      buffer.writeln('          <p>$paragraph</p>');
    }
    buffer.writeln('        </div>');
    buffer.writeln('      </section>');
    buffer.writeln();
  }

  buffer.write(
    sitePageClose(
      pl: pl,
      pageFile: 'privacy.html',
      note: pl
          ? 'Pytania i zgłoszenia: <a href="https://github.com/Frosttod/ARLS-ZA/issues">zgłoszenia w repozytorium</a>. Ta strona jest generowana przez <code>tool/build_privacy_pages.dart</code> z repozytorium gry, więc zmienia się razem z tym, co gra faktycznie robi.'
          : 'Questions and reports: <a href="https://github.com/Frosttod/ARLS-ZA/issues">the repository&rsquo;s issue tracker</a>. This page is generated by <code>tool/build_privacy_pages.dart</code> in the game repository, so it changes together with what the game actually does.',
    ),
  );

  return buffer.toString();
}

const List<_Part> _partsEn = [
  (
    id: 'collect',
    eyebrow: 'What is collected',
    heading: 'Nothing is sent, so nothing is collected',
    body: [
      'ARLS-ZA has no user accounts, no server of its own, no analytics SDK, no advertising SDK and no crash reporting. There is nowhere for your data to be sent, and nobody on the other end to receive it.',
      'Everything the game knows — your character&rsquo;s height, weight, age and sex, your position while you play, the route the simulation derived from it, your shelter, your inventory and your journal — is written to a database file inside the app&rsquo;s private storage on your own device.',
      'That file is excluded from Android&rsquo;s automatic cloud backup (<code>allowBackup=false</code>), specifically so that the location of the place you live is not copied off the phone by the operating system.',
    ],
  ),
  (
    id: 'location',
    eyebrow: 'Location',
    heading: 'Why the game reads your position',
    body: [
      'The game is played by walking. Your position is what moves the character, what burns their calories and water, what decides whether a search can be finished, and what the map draws. Without it there is no game to play.',
      'Position is read while you play and, if you allow it, while the app is in the background — a survival game that stops counting the moment the screen goes dark would tell you that you walked no further than your last glance at the phone. Background access is optional: refusing it leaves the game fully playable, counting your walk when you next open it.',
      'Position is used on the device and stored on the device. It is never transmitted, never shared with third parties and never sold. There is no mechanism in the app that could do any of those things.',
    ],
  ),
  (
    id: 'permissions',
    eyebrow: 'Permissions',
    heading: 'What each Android permission is for',
    body: [
      '<strong>Fine and coarse location</strong> — moving your character and drawing the map.',
      '<strong>Background location</strong> — continuing to count your walk with the screen off. Optional, and the game works without it.',
      '<strong>Foreground service, with location</strong> — the notification Android requires while the game counts a walk in the background. It is what stops the system killing the count mid-walk.',
      '<strong>Notifications</strong> — telling you that something in the game changed while you were away.',
    ],
  ),
  (
    id: 'network',
    eyebrow: 'Network',
    heading: 'The one thing that leaves the phone',
    body: [
      'The game downloads offline map packs so that it can draw your city with no connection at all. That download is an ordinary file request to the address listed in the app&rsquo;s map catalogue and, like any download, it tells the host serving the file that some device asked for it, including its IP address.',
      'Nothing about your character, your position or your play is attached to that request. There is no identifier, no cookie and no second request. Once a pack is downloaded the game runs with no network at all.',
    ],
  ),
  (
    id: 'deletion',
    eyebrow: 'Your data',
    heading: 'Deleting it',
    body: [
      'Uninstalling the app deletes everything it stored, because everything it stored lives inside the app&rsquo;s own private storage. There is no copy anywhere else to request, export or erase, and no account to close.',
      'Under the GDPR you have rights of access, rectification and erasure over personal data held about you. Here there is no personal data held by anybody but you, on your own device, and you can delete it at any moment.',
    ],
  ),
  (
    id: 'children',
    eyebrow: 'Age',
    heading: 'Who the game is for',
    body: [
      'ARLS-ZA is not directed at children. It asks a player to walk around a real city, at times including after dark, and its safety rules assume an adult judgement about whether a place and an hour are safe.',
    ],
  ),
  (
    id: 'changes',
    eyebrow: 'Changes',
    heading: 'If this policy changes',
    body: [
      'A change here follows a change in what the app does, never the other way round. The date at the top of this page is when the current version took effect; earlier versions are in the site&rsquo;s git history.',
    ],
  ),
];

const List<_Part> _partsPl = [
  (
    id: 'collect',
    eyebrow: 'Co jest zbierane',
    heading: 'Nic nie wychodzi, więc nic nie jest zbierane',
    body: [
      'ARLS-ZA nie ma kont użytkownika, nie ma własnego serwera, nie ma SDK analitycznego, nie ma SDK reklamowego i nie ma raportowania awarii. Nie ma dokąd wysłać twoich danych ani kto miałby je odebrać.',
      'Wszystko, co gra wie — wzrost, waga, wiek i płeć postaci, twoja pozycja w czasie gry, trasa wyliczona z niej przez symulację, schron, ekwipunek i dziennik — trafia do pliku bazy danych w prywatnej pamięci aplikacji na twoim urządzeniu.',
      'Ten plik jest wyłączony z automatycznej kopii zapasowej Androida (<code>allowBackup=false</code>) właśnie po to, żeby położenie miejsca, w którym mieszkasz, nie zostało skopiowane z telefonu przez system operacyjny.',
    ],
  ),
  (
    id: 'location',
    eyebrow: 'Lokalizacja',
    heading: 'Po co gra czyta twoją pozycję',
    body: [
      'W tę grę gra się chodząc. Twoja pozycja porusza postacią, spala jej kalorie i wodę, decyduje o tym, czy przeszukanie się dokończy, i rysuje mapę. Bez niej nie ma w co grać.',
      'Pozycja jest czytana w trakcie gry, a jeśli na to pozwolisz — także przy aplikacji w tle. Gra survivalowa, która przestaje liczyć w chwili zgaszenia ekranu, mówiłaby ci, że doszedłeś dokładnie tam, gdzie ostatni raz spojrzałeś w telefon. Dostęp w tle jest opcjonalny: odmowa zostawia grę w pełni grywalną, z doliczeniem spaceru przy następnym uruchomieniu.',
      'Pozycja jest używana na urządzeniu i przechowywana na urządzeniu. Nigdy nie jest przesyłana, udostępniana stronom trzecim ani sprzedawana. W aplikacji nie ma mechanizmu, który mógłby to zrobić.',
    ],
  ),
  (
    id: 'permissions',
    eyebrow: 'Uprawnienia',
    heading: 'Do czego służy każde uprawnienie Androida',
    body: [
      '<strong>Lokalizacja dokładna i przybliżona</strong> — poruszanie postacią i rysowanie mapy.',
      '<strong>Lokalizacja w tle</strong> — dalsze liczenie spaceru przy zgaszonym ekranie. Opcjonalne, gra działa i bez tego.',
      '<strong>Usługa pierwszoplanowa z lokalizacją</strong> — powiadomienie, którego Android wymaga, gdy gra liczy spacer w tle. To ono nie pozwala systemowi ubić liczenia w połowie drogi.',
      '<strong>Powiadomienia</strong> — informacja, że coś w grze zmieniło się pod twoją nieobecność.',
    ],
  ),
  (
    id: 'network',
    eyebrow: 'Sieć',
    heading: 'Jedyna rzecz, która opuszcza telefon',
    body: [
      'Gra pobiera pakiety map offline, żeby móc narysować twoje miasto zupełnie bez połączenia. To pobranie jest zwykłym żądaniem pliku pod adres wypisany w katalogu map aplikacji i — jak każde pobranie — mówi serwerowi wydającemu plik, że jakieś urządzenie o niego poprosiło, razem z jego adresem IP.',
      'Do tego żądania nie jest doklejane nic o twojej postaci, pozycji ani grze. Nie ma identyfikatora, nie ma ciasteczka, nie ma drugiego żądania. Po pobraniu pakietu gra działa całkowicie bez sieci.',
    ],
  ),
  (
    id: 'deletion',
    eyebrow: 'Twoje dane',
    heading: 'Usuwanie',
    body: [
      'Odinstalowanie aplikacji usuwa wszystko, co przechowywała, bo wszystko, co przechowywała, leży w jej własnej prywatnej pamięci. Nie ma gdzie indziej kopii, o którą trzeba by prosić, którą trzeba by eksportować albo kasować, ani konta, które trzeba by zamykać.',
      'RODO daje ci prawo dostępu do danych osobowych, ich sprostowania i usunięcia. Tutaj nie ma danych osobowych trzymanych przez nikogo poza tobą, na twoim własnym urządzeniu, i możesz je skasować w dowolnej chwili.',
    ],
  ),
  (
    id: 'children',
    eyebrow: 'Wiek',
    heading: 'Dla kogo jest ta gra',
    body: [
      'ARLS-ZA nie jest kierowana do dzieci. Wymaga chodzenia po prawdziwym mieście, czasem także po zmroku, a jej zasady bezpieczeństwa zakładają dorosłą ocenę tego, czy miejsce i pora są bezpieczne.',
    ],
  ),
  (
    id: 'changes',
    eyebrow: 'Zmiany',
    heading: 'Jeśli ta polityka się zmieni',
    body: [
      'Zmiana tutaj idzie za zmianą w tym, co robi aplikacja, nigdy odwrotnie. Data u góry strony to data wejścia w życie obecnej wersji; poprzednie wersje są w historii gita tej strony.',
    ],
  ),
];
